"""
Output Handling module for the User Chat Pipeline.

This module processes the candidate response text generated by the Context Engine.
It performs identity filtering, basic validation (non-empty, length, basic safety),
formats the response (primarily plain text/Markdown for V1), and returns the final
processed output ready for delivery.
"""

from selfy_core.user_pipeline.output_handling.processor import (
    OutputProcessor, setup_output_processor, get_output_processor
)
from selfy_core.user_pipeline.output_handling.validator import OutputValidator
from selfy_core.user_pipeline.output_handling.formatter import OutputFormatter
from selfy_core.user_pipeline.output_handling.data_structures import (
    OutputResult, ValidationResult, OutputValidationError
)

__all__ = [
    'OutputProcessor',
    'setup_output_processor',
    'get_output_processor',
    'OutputValidator',
    'OutputFormatter',
    'OutputResult',
    'ValidationResult',
    'OutputValidationError'
]